/*

Documento de los contenidos de Más allá de la Sombra.

*/

contenidoInteractivo = {
	titulo : "Más allá de la sombra", // Título de la página en general
	url : "http://", // URL de la página web
	descripcion : "", // Descripción de la página web
	bienvenida: {
		intro : "<p></p>"
	},
	total_cuadros : 2080, // Duración de fotogramas de la animación
	inicio_actos : 20, // Fotograma en el que inician los actos
	fin_actos : 20, // Fotograma en el que terminan los actos
	menu: [
		{
			url			: '#',
			titulo		: 'Sobre el proyecto',
		},
	],
	redes_sociales: [
		{
			url			: '#',
			icono			: 'assets/imgs/icon--facebook.svg',
			titulo		: 'facebook',
		},
		{
			url			: '#',
			icono			: 'assets/imgs/icon--linkedin.svg',
			titulo		: 'linkedin',
		},
		{
			url			: '#',
			icono			: 'assets/imgs/icon--twitter.svg',
			titulo		: 'twitter',
		},
	],
	creditos: 'MCCI, NODO',
	actos: [
		{
			anio: '2017',
			eventos: [
				{
					titulo		: 'Es detenido el exgobernador Roberto Borge en Panamá antes de abordar un vuelo a París.',
					fecha			: '4 de junio de 2017',
					iframe 		: true,
					fuente		: 'http://www.eluniversal.com.mx/articulo/estados/2017/06/5/detienen-roberto-borge-en-panama',
				},
				{
					titulo		: 'Empresario "Rey de los dragones" simula contratos de autobuses a sobrecosto con el gobierno de Chihuahua',
					fecha			: '3 de junio de 2017',
					iframe 		: true,
					fuente		: 'http://www.reforma.com/aplicaciones/articulo/default.aspx?id=1129047&v=5',
				},
				{
					titulo		: 'Giran orden de aprehensión contra del exgobernador Quintana Roo Roberto Borge',
					fecha			: '3 de junio de 2017',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2017/06/ordenan-detener-roberto-borge/',
				},
				{
					titulo		: 'Son detenidos José Manuel Saiz Pineda, extesorero de Granier en Tabasco, y su esposa. Poseían 7 propiedades de lujo en EUA, valuadas en 39.2 MDD',
					fecha			: '31 de mayo de 2017',
					iframe 		: true,
					fuente		: 'http://www.reforma.com/aplicaciones/articulo/default.aspx?id=1126440&v=5',
				},
				{
					titulo		: 'Fiscalía de  Chihuahua y SFP revelan que exgobernador César Duarte desvió más de 360 MDP al PRI',
					fecha			: '29 de mayo de 2017',
					iframe 		: true,
					fuente		: 'http://www.reforma.com/aplicaciones/articulo/default.aspx?id=1124686',
				},
				{
					titulo		: 'Alcaldes de Puebla son acusados de ser dueños de gasolinerías y haber comprado a huachicoleros',
					fecha			: '25 de mayo de 2017',
					iframe 		: true,
					fuente		: 'http://www.eluniversal.com.mx/articulo/nacion/seguridad/2017/05/25/ven-ligas-de-alcaldes-con-huachicoleros',
				},
				{
					titulo		: 'Denuncian intervención de dependencias federales en la campaña del PRI en Edomex.',
					fecha			: '21 de mayo de 2017',
					iframe 		: true,
					fuente		: 'http://www.reforma.com/aplicaciones/articulo/default.aspx?id=1118601',
				},
				{
					titulo		: 'Humberto Moreira y familiares transfirieron 63 MDD a cuentas irregulares el extranjero entre 2013 y 2016. El exgobernador denuncia penalmente a medios por difamación.',
					fecha			: '16 de mayo de 2017',
					iframe 		: true,
					fuente		: 'http://www.reforma.com/aplicaciones/articulo/default.aspx?id=1114584',
				},
				{
					titulo		: 'Ficrea niega haber recibido los 158 mdp que el gobierno de Coahuila sostiene que depósito entre 2013 y 2014.',
					fecha			: '13 de mayo de 2017',
					iframe 		: true,
					fuente		: 'http://www.reforma.com/aplicaciones/articulo/default.aspx?id=1112481',
				},
				{
					titulo		: 'Iniciativa "Ahora" presenta denuncia ante PGR por presunta red de corrupción que involucra a OHL y financiamiento de campañas políticas del PRI en el Edomex.',
					fecha			: '9 de mayo de 2017',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2017/05/pri-ohl-corrupcion-del-mazo/',
				},
				{
					titulo		: 'Durante la gestión de Miguel Ángel Riquelme como alcalde de Torreón, dos constructores obtuvieron contratos por 88 mdp.',
					fecha			: '4 de mayo de 2017',
					fuente		: '#',
				},
				{
					titulo		: 'COFECE impone multa histórica con 1,100 MDP a 4 afores por colusión en manejo de cuentas de ahorro.',
					fecha			: '4 de mayo de 2017',
					iframe 		: true,
					fuente		: 'http://www.elfinanciero.com.mx/economia/las-afore-reciben-multa-historica.html',
				},
				{
					titulo		: 'Revela esquema de corrupción entre empresas y altos funcionarios de CAPUFE, entre 2013 y 2016, en la asignación de contratos de obra pública por 770 MPD.',
					fecha			: '3 de mayo de 2017',
					iframe 		: true,
					fuente		: 'https://contralacorrupcion.mx/web/capufeleaks/',
				},
				{
					titulo		: 'Diputados no resuelven sobre desafuero de diputado PRI Tarek Abdalá, acusado por Fiscalía estatal de desvío de 23 mil MDP cuando era tesorero de VER.',
					fecha			: '27 de abril de 2017',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2017/04/tarek-desafuero-diputados/',
				},
				{
					titulo		: 'Luis Reynoso Femat, exgobernador AGS, acusado por tribunal federal en EUA por devío de 5.5 MDD de recursos públicos para adquirir propiedades en San Antonio, Texas.',
					fecha			: '25 de abril de 2017',
					iframe 		: true,
					fuente		: 'http://www.eluniversal.com.mx/articulo/nacion/politica/2017/04/25/acusan-en-eu-reynoso-femat-de-transferir-ilegalmente-55-mdd',
				},
				{
					titulo		: 'Difunden primer video en el que Eva Cadena, candidata de Morena a la presidencia municipal de Las Choapas, VER, recibe dinero "para AMLO". Tres videos más se publican en siguientes semanas.',
					fecha			: '24 de abril de 2017',
					iframe 		: true,
					fuente		: 'http://www.eluniversal.com.mx/articulo/nacion/politica/2017/04/24/representante-de-morena-recauda-dinero-para-amlo',
				},
				{
					titulo		: 'velan que OHL México fue intermediario para el pago de un "moche" en España por 1.4 MDEuros.',
					fecha			: '21 de abril de 2017',
					iframe 		: true,
					fuente		: 'http://www.reforma.com/aplicaciones/articulo/default.aspx?id=1095761',
				},
				{
					titulo		: 'Javier Duarte, exgobernador VER, detenido en Panajachel, Guatemala, acusado de enriquecimiento ilícito y delincuencia organizada.',
					fecha			: '15 de abril de 2017',
					iframe 		: true,
					fuente		: 'http://www.univision.com/noticias/arrestos/javier-duarte-exgobernador-de-veracruz-fue-detenido-segun-informo-la-pgr',
				},
				{
					titulo		: 'Tomás Yarrington, exgobernador TAMPS, detenido en Florencia, Italia, acusado de delincuencia organizada y operaciones con recursos de procedencia ilícita.',
					fecha			: '10 de abril de 2017',
					iframe 		: true,
					fuente		: 'http://www.excelsior.com.mx/nacional/2017/04/10/1156879',
				},
				{
					titulo		: 'Revelan que Guillermo Anaya, candidato a gobernador (PAN COAH) posee mansión de 20 MDP y no ha presentado #3de3.',
					fecha			: '6 de abril de 2017',
					iframe 		: true,
					fuente		: 'http://www.elfinanciero.com.mx/nacional/el-candidato-anaya-tiene-casa-de-20-mdp-y-no-presenta-3de3.html',
				},
				{
					titulo		: 'Interpol busca a exgobernador de Chihuahua, César Duarte, prófugo y acusado de peculado.',
					fecha			: '31 de marzo de 2017',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2017/03/interpol-ficha-roja-cesar-duarte/',
				},
				{
					titulo		: 'Presunto abusador de menor en Veracruz recibe amparo por mala integración del expediente. Reclamo social provoca que juez sea investigado por el Consejo de la Judicatura.',
					fecha			: '28 de marzo de 2017',
					iframe 		: true,
					fuente		: 'http://www.eluniversal.com.mx/articulo/estados/2017/03/28/amparan-uno-de-los-porkys-y-ordenan-su-libertad',
				},
				{
					titulo		: 'Fiscal de Nayarit, Édgar Veytia, detenido en San Diego por orden de un jurado federal de EUA, acusado por narcotráfico.',
					fecha			: '28 de marzo de 2017',
					fuente		: 'Reforma primera plana jueves 30 de marzo.',
				},
				{
					titulo		: 'Exfuncionario de Chihuahua, Antonio Enrique Tarín, acusado penalmente por peculado, se refugia en Cámara de Diputados esperando amparo. Pretendía asumir escaño como diputado del PRI.',
					fecha			: '28 de marzo de 2017',
					fuente		: 'Reforma primera plana jueves 30 de marzo.',
				},
				{
					titulo		: 'En pleno proceso de selección de fiscal anticorrupción, dos aspirantes presentan ensayos con párrafos idénticos entre sí.',
					fecha			: '16 de marzo de 2017',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2017/03/aspirantes-fiscal-anticorrupcion-copian-ensayo/',
				},
				{
					titulo		: 'Flavino Ríos, exgobernador interino de Veracruz, investigado por encubrir a Javier Duarte y desviar 2,200 MDP.',
					fecha			: '14 de marzo de 2017',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2017/03/veracruz-duarte-corrupcion/',
				},
				{
					titulo		: 'Universidad Autónoma de Nayarit publica lista de aviadores en su nómina, entre los que aparecen funcionarios estatales de los poderes ejecutivo y judicial.',
					fecha			: '9 de marzo de 2017',
					iframe 		: true,
					fuente		: 'http://www.nayaritaltivo.com.mx/nota.php?id=4846',
				},
				{
					titulo		: 'Revelan que Key Energy pagó 9 MDP en sobornos para obtener contratos en pozos de Pemex.',
					fecha			: '9 de marzo de 2017',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2017/03/pemex-sobornos-facturas/',
				},
				{
					titulo		: 'Revelan que José Manzur Quiroga, Secretario de Gobierno en EDOMEX, posee un rancho con zoológico, 136 autos y un lago artificial.',
					fecha			: '6 de marzo de 2017',
					iframe 		: true,
					fuente		: 'http://www.sinembargo.mx/06-03-2017/3166174',
				},
				{
					titulo		: 'Revelan que David Korenfeld, extitular de CONAGUA, dio contratos por 25 MDP a universidad en Israel en 2015, institución que ese mismo año le otorgó un doctorado honoris causa.',
					fecha			: '28 de febrero de 2017',
					iframe 		: true,
					fuente		: 'http://www.eluniversal.com.mx/articulo/nacion/politica/2017/02/28/korenfeld-dio-contratos-por-25-mdp-universidad-que-le-otorgo',
				},
				{
					titulo		: 'Revelan más contratos para los amigos de la hija de Ricardo Monreal: suman 27 millones de pesos en 16 contratos.',
					fecha			: '27 de febrero de 2017',
					iframe 		: true,
					fuente		: 'https://contralacorrupcion.mx/noticias/nuevoscontratos/',
				},
				{
					titulo		: 'Braskem, mayor petrolera LatAm recorta inversión en México debido a multas por corrupción.',
					fecha			: '22 de febrero de 2017',
					iframe 		: true,
					fuente		: 'http://eleconomista.com.mx/industrias/2017/02/22/braskem-recorta-inversion-mexico-debido-multas-corrupcion',
				},
				{
					titulo		: 'Revelan sobornos de Odebrecht y subsidiarias a funcionarios de PEMEX por 10.5 MDD para obtener contratos entre 2010 y 2016.',
					fecha			: '15 de febrero de 2017',
					iframe 		: true,
					fuente		: 'http://aristeguinoticias.com/1502/mexico/la-negra-relacion-de-odebrecht-y-pemex/',
				},
				{
					titulo		: 'Revelan que Ricardo Monreal, delegado en Cuauhtémoc, CDMX, otorgó contratos millonarios a empresas sin experiencia demostrada.',
					fecha			: '15 de febrero de 2017',
					iframe 		: true,
					fuente		: 'http://www.radioformula.com.mx/notas.asp?Idn=662569&idFC=2017 http://www.animalpolitico.com/2017/02/monreal-contratos-hija-empresas/',
				},
				{
					titulo		: 'Revelan que exgobernador de Chiapas Juan Sabines contrató red de empresas fantasma de Veracruz por 118 MDP entre 2010 y 2013.',
					fecha			: '13 de febrero de 2017',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2017/02/empresa-fantama-chiapas-sabines/',
				},
				{
					titulo		: 'Rodrigo Medina, exgobernador de Nuevo León, detenido por peculado y daño patrimonial al estado; liberado por amparo horas después.',
					fecha			: '26 de enero de 2017',
					iframe 		: true,
					fuente		: 'http://eleconomista.com.mx/sociedad/2017/01/26/detienen-liberan-mismo-dia-rodrigo-medina',
				},
				{
					titulo		: 'Informe sobre Cuenta Pública 2015 revela que en remodelación del hangar presidencial se hicieron pagos irregulares por 59 MDP a empresa.',
					fecha			: '18 de enero de 2017',
					iframe 		: true,
					fuente		: 'http://aristeguinoticias.com/1801/mexico/grupo-higa-encarecio-costos-de-hangardeepn-por-59-mdp-auditoria-superior/',
				},
				{
					titulo		: 'Investigaciones oficiales en Veracruz revelan que durante administración de exgobernador Javier Duarte se compraron quimios y pruebas de VIH inservibles.',
					fecha			: '16 de enero de 2017',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2017/01/yunes-veracruz-falsas-quimioterapias/',
				},
				{
					titulo		: 'Puebla deberá pagar 47 mil MDP en compromisos financieros contraídos por el exgobernador Moreno Valle, que no contemplados como deuda.',
					fecha			: '16 de enero de 2017',
					iframe 		: true,
					fuente		: 'https://contralacorrupcion.mx/informate/rafael-moreno-valle-esconde-una-deuda-publica-multimillonaria-los-poblanos-deberan-pagar/',
				},
				{
					titulo		: 'Secretario de Energía, Pedro Joaquín, tiene gasolinerías en Cozumel, algunas clausuradas por vender litros incompletos y alterar bombas',
					fecha			: '10 de enero de 2017',
					iframe 		: true,
					fuente		: 'http://m.aristeguinoticias.com/1001/mexico/gasolinazo-titular-de-energia-no-da-litros-de-a-litro-y-jefe-de-profeco-verifica-a-su-familia/',
				},
			],
		},
		{
			anio: '2016',
			eventos : [
				{
					titulo		: 'Fiscal General de QRoo, Carlos Álvarez, renuncia sin investigar a exgobernador Roberto Borge.',
					fecha			: '8 de diciembre de 2016',
					iframe 		: true,
					fuente		: 'http://www.sinembargo.mx/09-12-2016/3123937',
				},
				{
					titulo		: 'Revelan depredación inmobiliaria en la delegación Cuauhtémoc, dañando patrimonio arquitectónico de la zona.',
					fecha			: '1 de diciembre de 2016',
					iframe 		: true,
					fuente		: 'http://www.nexos.com.mx/?p=30466',
				},
				{
					titulo		: 'Revelan que Josefina Vázquez Mota viajó a EUA con dinero para repatriar mexicanos',
					fecha			: '28 de noviembre de 2016',
					iframe 		: true,
					fuente		: 'https://contralacorrupcion.mx/informate/fondo-repatriacion-mexicanos-vazquez-mota-justifica-viajes/',
				},
				{
					titulo		: 'PGR congela cuentas de suegros de Javier Duarte por investigación de delitos fiscales, financieros y lavado de dinero.',
					fecha			: '31 de octubre de 2016',
					iframe 		: true,
					fuente		: 'http://www.reforma.com/aplicacioneslibre/preacceso/articulo/default.aspx?id=973411&v=6&urlredirect=http://www.reforma.com/aplicaciones/articulo/default.aspx?id=973411&v=6',
				},
				{
					titulo		: 'Gobernador interino confirma solicitud de rescate financiero de VER por 11 MMP a SHCP.',
					fecha			: '30 de octubre de 2016',
					iframe 		: true,
					fuente		: 'http://www.milenio.com/estados/Flavino-Rios-reconoce-alcaldes-Veracruz_0_838716388.html',
				},
				{
					titulo		: 'PGR anuncia que, tras obtener orden de aprehensión, Javier Duarte está prófugo.',
					fecha			: '20 de octubre de 2016',
					iframe 		: true,
					fuente		: 'http://tiempo.com.mx/noticia/57533-oficialmente_javier_duarte_ya_/1',
				},
				{
					titulo		: 'Interpol emite alerta para detener a Guillermo Padrés, prófugo por delitos fiscales y operaciones con recursos de procedencia ilícita.',
					fecha			: '15 de octubre de 2016',
					iframe 		: true,
					fuente		: 'http://www.redpolitica.mx/estados/confirman-que-padres-es-profugo-de-la-justicia',
				},
				{
					titulo		: 'Revelan excesos y nepotismo de Claudia Acompa #LadyGucci, alcaldesa de Santiago Tuxtla, VER',
					fecha			: '11 de octubre de 2016',
					iframe 		: true,
					fuente		: 'http://www.eluniversal.com.mx/articulo/estados/2016/10/11/ladygucci-una-historia-de-anomalias-y-escandalos',
				},
				{
					titulo		: 'Enrique Ochoa, dirigente nacional del PRI, otorgó contratos por 500 MDP a consultora sin licitación en 2015 cuando era titular de CFE.',
					fecha			: '11 de octubre de 2016',
					iframe 		: true,
					fuente		: 'http://www.proceso.com.mx/458297/ochoa-reza-otorgo-jugosos-contratos-sin-licitacion',
				},
				{
					titulo		: 'Investiga PGR a Padrés, exgobernador SON, y a su abogado, el exprocurador Antonio Lozano Gracia, por lavado de dinero.',
					fecha			: '4 de octubre de 2016',
					iframe 		: true,
					fuente		: 'http://www.huffingtonpost.com.mx/2016/10/04/padres-profugo-de-la-justicia/',
				},
				{
					titulo		: 'Revelan que EPN ha llevado a familiares y amigos en giras presidenciales internacionales desde 2013.',
					fecha			: '2 de octubre de 2016',
					iframe 		: true,
					fuente		: 'http://aristeguinoticias.com/0210/mexico/viaja-epn-con-familia-y-amigos-en-giras-internacionales/',
				},
				{
					titulo		: 'Denuncian corrupción en adquisición de TVs por 1,300 MDD en el marco de la Estrategia Digital Nacional.',
					fecha			: '28 de septiembre de 2016',
					iframe 		: true,
					fuente		: 'http://www.wsj.com/articles/mexicos-tv-giveaway-spawns-questions-1475103213',
				},
				{
					titulo		: 'Revelan que AMLO omitió en su #3de3 dos departamentos en la CDMX.',
					fecha			: '27 de septiembre de 2016',
					iframe 		: true,
					fuente		: 'http://www.wsj.com/articles/mexican-presidential-hopeful-andres-manuel-lopez-obrador-failed-to-disclose-all-his-assets-1475018561',
				},
				{
					titulo		: 'Revelan que el gobierno de Rubén Moreira (COAH) paga decenas de MDP del erario a empresas fantasma.',
					fecha			: '26 de septiembre de 2016',
					iframe 		: true,
					fuente		: 'http://www.reforma.com/libre/acceso/acceso.htm?urlredirect=/aplicaciones/articulo/default.aspx?id=947963',
				},
				{
					titulo		: 'Revelan que Roberto Borge, gobernador de QROO, es propietario de inmuebles en zonas de lujo con un valor de un MDD.',
					fecha			: '19 de septiembre de 2016',
					iframe 		: true,
					fuente		: 'http://noticieros.televisa.com/programas-10-punto-denise-maerker/#153946_613627_20160916',
				},
				{
					titulo		: 'Revelan uso privado de aerolínea paraestatal de QROO para traslado de políticos locales, estructura del PRI y sus familiares',
					fecha			: '19 de septiembre de 2016',
					iframe 		: true,
					fuente		: 'http://noticieros.televisa.com/programas-despierta-carlos-loret-mola/2016-09-19/gobernador-quintana-roo-tiene-su-propia-aerolinea/',
				},
				{
					titulo		: 'Revelan asignación de contratos federales en beneficio de ocho empresarios mexiquenses cercanos a EPN durante los últimos 4 años.',
					fecha			: '17 de septiembre de 2016',
					iframe 		: true,
					fuente		: 'http://www.proceso.com.mx/455369/las-fortunas-mexiquenses-del-penanietismo',
				},
				{
					titulo		: 'Colaborador de Ricardo Monreal en delegación Cuauhtémoc (CDMX) detenido por no acreditar la propiedad de 600 mil pesos en efectivo.',
					fecha			: '16 de septiembre de 2016',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2016/09/detienen-mano-derecha-monreal-600-mil-pesos-efectivo/',
				},
				{
					titulo		: 'Revelan que Fernando Velasco, primo del Srio. Particular de EPN, cobró sin trabajar durante 19 meses en el consulado de Los Ángeles.',
					fecha			: '13 de septiembre de 2016',
					iframe 		: true,
					fuente		: 'http://www.m-x.com.mx/2016-09-13/empresario-mexiquense-vinculado-a-pena-nieto-es-aviador-en-el-consulado-mexicano-en-los-angeles-audio/',
				},
				{
					titulo		: 'Revelan que Francisco Olvera, exgobernador de HGO, otorgó 25 MDP en contratos públicos al operador financiero de su campaña.',
					fecha			: '12 de septiembre de 2016',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2016/09/contratos-millonarios-hidalgo-francisco-olvera-mersi/',
				},
				{
					titulo		: 'INE abre investigación al PSD por presunto pago de 7 MDP a Cuauhtémoc Blanco para ser candidato por Cuernavaca.',
					fecha			: '30 de agosto de 2016',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2016/08/psd-contrato-cuauhtemoc-blanco-7-mdp-candidato-cuernavaca/',
				},
				{
					titulo		: 'Revelan que PSD firmó contrato con Cuauhtémoc Blanco por 7 MDP para contender por la alcaldía de Cuernavaca.',
					fecha			: '25 de agosto de 2016',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2016/08/psd-contrato-cuauhtemoc-blanco-7-mdp-candidato-cuernavaca/',
				},
				{
					titulo		: 'Revelan supuesto enriquecimiento inexplicable de César Duarte, gobernador saliente de CHIH.',
					fecha			: '22 de agosto de 2016',
					iframe 		: true,
					fuente		: 'http://segundoasegundo.com/televisa-muestra-la-fortuna-inexplicable-cesar-duarte/',
				},
				{
					titulo		: 'Denuncian despojos y desalojos en QROO por hombres vinculados al gobernador saliente, Roberto Borge.',
					fecha			: '16 de agosto de 2016',
					iframe 		: true,
					fuente		: 'https://www.nytimes.com/2016/08/17/world/americas/mexico-tulum-corruption-evictions.html?_r=0',
				},
				{
					titulo		: 'Juez ordena juicio penal contra Rodrigo Medina, exgobernador de NL, por ejercicio ilegal de funciones.',
					fecha			: '9 de agosto de 2016',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2016/08/exgobernador-medina-libra-peculado-inician-juicio-otro-delito/',
				},
				{
					titulo		: 'Xóchitl Gálvez, delegada de Miguel Hidalgo (CDMX), interpone denuncia penal contra administración anterior por malversación de 16 MDP.',
					fecha			: '15 de julio de 2016',
					iframe 		: true,
					fuente		: 'http://www.excelsior.com.mx/comunidad/2016/07/15/1105025',
				},
				{
					titulo		: 'Revelan que red de funcionarios y notarios vinculados al gobernador Roberto Borge arrebata el patrimonio a empresas y particulares desde 2014 en QROO.',
					fecha			: '6 de julio de 2016',
					iframe 		: true,
					fuente		: 'http://expansion.mx/nacional/2016/07/06/los-piratas-de-borge-el-saqueo-de-bienes-institucionalizado-en-quintana-roo',
				},
				{
					titulo		: 'Revelan que empresas de la familia del exprocurador Murillo Karam fueron beneficiadas con contratos públicos por 300 MDD.',
					fecha			: '23 de junio de 2016',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2016/06/los-43-contratos-que-ponen-contra-la-pared-a-murillo/',
				},
				{
					titulo		: 'Revelan que el gobierno de GTO pagó sobreprecio de 290 MDP por terrenos que después regaló a Toyota.',
					fecha			: '9 de junio de 2016',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2016/06/el-gobierno-de-guanajuato-paga-tierras-a-sobreprecio-para-regalarlas-a-toyota/',
				},
				{
					titulo		: 'Acusan a gobierno de Miguel Mancera (CDMX) por desvío de recursos públicos en beneficio del PRD.',
					fecha			: '30 de mayo de 2016',
					iframe 		: true,
					fuente		: 'http://www.vanguardia.com.mx/articulo/denuncia-morena-mancera-por-presunto-desvio-de-500-mdp-al-prd',
				},
				{
					titulo		: 'Gobierno de Javier Duarte (VER) entregó 645 MDP a 21 empresas fantasma durante 2012 y 2013; doce notarios públicos vinculados al PRI involucrados',
					fecha			: '8 de junio- 24 de mayo de 2016',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2016/05/hay-irregularidades-en-las-firmas-de-los-contratos-de-la-red-de-empresas-en-veracruz-grafologo/',
				},
				{
					titulo		: 'Revelan que ANEAS, organización que recibió 93 MDP de CONAGUA durante gestión de David Korenfeld, financia centro de estudios en Univ. de Nuevo México en su honor.',
					fecha			: '26 de mayo de 2016',
					iframe 		: true,
					fuente		: 'http://aristeguinoticias.com/2605/mexico/con-recursos-de-conagua-korenfeld-financio-organizacion-que-ahora-preside/',
				},
				{
					titulo		: 'Hijo de Miguel Ángel Yunes, candidato a gobernador (VER), adquirió propiedades por 80 MDP con empresas fachada.',
					fecha			: '22 de mayo de 2016',
					iframe 		: true,
					fuente		: 'http://www.m-x.com.mx/2016-05-22/la-bicentenaria-fortuna-de-omar-yunes/',
				},
				{
					titulo		: '68 entidades financieras, 289 nombres y 39 intermediarios vinculados a México en los Panama Papers.',
					fecha			: '10 de mayo de 2016',
					iframe 		: true,
					fuente		: 'http://www.milenio.com/politica/Panama_Papers_Mexico-empresas_Mexico_Panama_Papers-Panama_Papers_mexicanos_0_734926564.html',
				},
				{
					titulo		: 'Bernardo Quezada, diputado federal, gastó 8.2 MDD en propiedades en EUA de 2004 a 2008.',
					fecha			: '17 de abril de 2016',
					iframe 		: true,
					fuente		: 'http://www.miamiherald.com/news/business/real-estate-news/article72068697.html',
				},
				{
					titulo		: 'Rafael Moreno Valle, gobernador de PUE, comprometió ingresos del ISR por 50 años en un fideicomiso administrado por una empresa.',
					fecha			: '2 de febrero de 2016',
					iframe 		: true,
					fuente		: 'http://www.reforma.com/aplicacioneslibre/preacceso/articulo/default.aspx?id=756238&urlredirect=http://www.reforma.com/aplicaciones/articulo/default.aspx?id=756238',
				},
				{
					titulo		: 'Humberto Moreira detenido en Madrid por lavado de dinero y organización criminal.',
					fecha			: '15 de enero de 2016',
					iframe 		: true,
					fuente		: 'http://internacional.elpais.com/internacional/2016/01/15/mexico/1452876054_142959.html',
				},
			],
		},
		{
			anio: '2015',
			eventos : [
				{
					titulo		: 'Constructores chiapanecos denuncian que el gobierno de Manuel Velasco favorece a amigos con contratos de obra pública.',
					fecha			: '24 de noviembre de 2015',
					iframe 		: true,
					fuente		: 'http://www.proceso.com.mx/421663/el-circulo-de-manuel-velasco-se-enriquece-con-la-obra-publica',
				},
				{
					titulo		: 'Jaime Rodríguez, gobernador electo de NL, denuncia contrato irregular de Rodrigo Medina, gobernador saliente, con la automotriz KIA.',
					fecha			: '20 de noviembre de 2015',
					iframe 		: true,
					fuente		: 'http://www.proceso.com.mx/421235/denuncia-el-bronco-contrato-ventajoso-entre-medina-y-kia-motors',
				},
				{
					titulo		: 'Guillermo Padrés, exgobernador (SON), acusado de haber adquirido uniformes escolares con un sobrecosto de 50%.',
					fecha			: '9 de noviembre de 2015',
					iframe 		: true,
					fuente		: 'http://www.elimparcial.com/EdicionEnlinea/Notas/Sonora/09112015/1025549-Infla-Padres-Elias-compra-de-uniformes-chinos-senala-secretario-de-Economia.html',
				},
				{
					titulo		: 'Diputados acusan a Miguel Ángel Yunes, precandidato a gobernador (VER), por enriquecimiento ilícito por 100 MDP.',
					fecha			: '4 de septiembre de 2015',
					iframe 		: true,
					fuente		: 'http://www.elfinanciero.com.mx/nacional/pri-revela-cuentas-de-yunes-linares-por-mas-de-100-millones-de-pesos.html',
				},
				{
					titulo		: 'Madre de Manuel Velasco, gobernador de CHIS, recibe 11.3 MDP por cargo honorífico en el DIF estatal a lo largo de tres años.',
					fecha			: '4 de agosto de 2015',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2015/08/mama-de-manuel-velasco-recibe-apoyo-de-3-9-millones-de-pesos-otorgado-por-el-dif-de-chiapas/',
				},
				{
					titulo		: 'Lucero Sánchez, diputada local (SIN), acusada de falsificar documentos para ingresar al penal del Altiplano para visitar a El Chapo.',
					fecha			: '16 de julio de 2015',
					iframe 		: true,
					fuente		: 'http://www.excelsior.com.mx/nacional/2015/07/16/1035002',
				},
				{
					titulo		: 'Edomex otorgó sin auditar 1,700 MDP a Fundación Proacceso y Enova a lo largo de seis años para la creación de una plataforma digital educativa.',
					fecha			: '7 de julio de 2015',
					iframe 		: true,
					fuente		: 'http://www.nexos.com.mx/?p=25525',
				},
				{
					titulo		: 'Investigación en Texas contra Humberto Moreira por lavado de dinero robado de las arcas estatales.',
					fecha			: '30 de junio de 2015',
					iframe 		: true,
					fuente		: 'http://www.expressnews.com/news/local/article/Court-records-Former-Mexican-governor-stole-6358246.php',
				},
				{
					titulo		: 'Audio de Ricardo Monreal, candidato a delegado (DF), y Néstor Núñez, su coordinador de campaña, hablando de falsear gastos.',
					fecha			: '25 de mayo de 2015',
					iframe 		: true,
					fuente		: 'http://www.excelsior.com.mx/comunidad/2015/05/25/1025941',
				},
				{
					titulo		: 'Victor Hugo Romo, exdelegado de Miguel Hidalgo (DF), acusado de encabezar red de corrupción inmobiliaria e invasión de predios.',
					fecha			: '19 de mayo de 2015',
					iframe 		: true,
					fuente		: 'http://lasillarota.com/victor-hugo-romo-negocio-predio-con-los-claudios#.V7OhRxXhAdU',
				},
				{
					titulo		: 'Filtran audios de funcionarios mexiquenses y directivos de OHL en los que se coluden para obtener beneficios del Viaducto Elevado Bicentenario y Circuito Exterior Mexiquense.',
					fecha			: '7 de mayo de 2015',
					iframe 		: true,
					fuente		: 'http://www.forbes.com.mx/esta-es-la-grabacion-que-derrumbo-las-acciones-de-ohl-mexico/#gs.VajiHBs',
				},
				{
					titulo		: 'Denuncian en redes a David Korenfeld, director de CONAGUA, por utilizar helicóptero oficial para su uso privado.',
					fecha			: '29 de marzo de 2015',
					iframe 		: true,
					fuente		: 'http://www.eluniversal.com.mx/articulo/nacion/politica/2016/01/29/korenfeld-usaba-helicoptero-de-conagua-al-estilo-uber',
				},
				{
					titulo		: 'Regidores de Pesquería, NL, denuncian penalmente al alcalde por modificar uso de suelo en terrenos donados a la automotriz KIA.',
					fecha			: '3 de marzo de 2015',
					iframe 		: true,
					fuente		: 'http://eleconomista.com.mx/estados/2015/03/03/kia-se-eleva-1000-costo-terrenos',
				},
				{
					titulo		: 'Audio de Mauricio Trejo, alcalde de San Miguel de Allende, GTO, evidencia asignación amañada de contratos de obra pública.',
					fecha			: '17 de febrero de 2015',
					iframe 		: true,
					fuente		: 'http://www.excelsior.com.mx/nacional/2015/02/17/1008751',
				},
				{
					titulo		: 'Revelan que José Murat, ex gobernador de Oaxaca, posee lujosas propiedades en EUA.',
					fecha			: '10 de febrero de 2015',
					iframe 		: true,
					fuente		: 'http://www.nytimes.com/2015/02/11/nyregion/jose-murat-casab-mexico-pri-luxury-condos-us.html?module=TranslationLink&_r=0',
				},
				{
					titulo		: 'Suspensión definitiva del tren MEX-QRO. México pagó 500 MDP en estudios de factibilidad e indemniza con 16 MDD al gobierno de China.',
					fecha			: '30 de enero de 2015',
					iframe 		: true,
					fuente		: 'http://www.milenio.com/negocios/suspension_tren_rapido-tren_Mexico-Queretaro-trenes_de_pasajeros-Luis_Videgaray_0_455354570.html',
				},
				{
					titulo		: 'Ricardo Monreal, candidato a delegado (DF), acusa a Rafael Moreno Valle, gobernador PUE, de favorecer a Grupo Higa con contratos por 26 mil MDP.',
					fecha			: '23 de enero de 2015',
					iframe 		: true,
					fuente		: 'https://docs.google.com/spreadsheets/d/Env%C3%ADo%20a%20Nexos%2030sep2016/-%09http:/www.noticiasmvs.com#!/noticias/denuncian-corrupcion-y-conflictos-de-interes-entre-moreno-valle-e-higa-304',
				},
				{
					titulo		: 'Edgar Borja, asambleísta en el DF, expulsado del PAN tras difusión de video en que negocia licitaciones para su beneficio.',
					fecha			: '6 de enero de 2015',
					iframe 		: true,
					fuente		: 'http://www.excelsior.com.mx/comunidad/2015/01/06/1000995',
				},
				{
					titulo		: 'Simón Vicente Pacheco, alcalde de Charapan, MICH, detenido por enriquecimiento ilícito.',
					fecha			: '6 de enero de 2015',
					iframe 		: true,
					fuente		: 'http://expansion.mx/nacional/2015/01/06/un-alcalde-del-prd-en-michoacan-detenido-por-enriquecimiento-ilicito',
				},
				{
					titulo		: 'José Ricardo Gallardo, alcalde de Soledad de Graciano Sánchez, SLP, detenido por desvío de 200 MDP y lavado de dinero del crimen organizado.',
					fecha			: '6 de enero de 2015',
					iframe 		: true,
					fuente		: 'http://www.milenio.com/policia/alcalde_Soledad_de_Graciano_Sanchez-Jose_Ricardo_Gallardo_Cardona-alcalde_SLP_0_440956252.html',
				},
				{
					titulo		: 'Video muestra a Noé Miguel Marín, Secretario municipal en QRO, solicitando dinero a proveedores para conceder contratos.',
					fecha			: '5 de enero de 2015',
					iframe 		: true,
					fuente		: 'http://www.sinembargo.mx/05-01-2015/1208587',
				},
			],
		},
		{
			anio: '2014',
			eventos : [
				{
					titulo		: 'Jesús Valencia Guzmán, delegado de Iztapalapa, hace uso privado de camioneta de proveedor de la delegación y choca.',
					fecha			: '17 de diciembre de 2014',
					iframe 		: true,
					fuente		: 'http://www.20minutos.com.mx/noticia/20583/0/jesus-valencia/delegado-iztapalapa/accidente-camioneta-contratista/',
				},
				{
					titulo		: 'Revelan que Luis Videgaray, Secretario de Hacienda, adquirió casa en Malinalco por medio de un crédito con Grupo Higa.',
					fecha			: '12 de diciembre de 2014',
					iframe 		: true,
					fuente		: 'https://www.wsj.com/articles/new-ties-emerge-between-mexico-government-and-builder-1418344492',
				},
				{
					titulo		: 'Diputados declaran que EPN sobrepasó 13 veces el tope de campaña con tarjetas de MONEX.',
					fecha			: '12 de marzo de 2014',
					iframe 		: true,
					fuente		: 'http://aristeguinoticias.com/1203/mexico/caso-monex-pri-gasto-mas-de-4-mil-500-millones-de-pesos-en-campana-de-2012/',
				},
				{
					titulo		: 'Línea 12 del Metro en DF cerrada por fallas en el sistema eléctrico en rieles elevados a seis meses de inaugurada.',
					fecha			: '11 de marzo de 2014',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2014/03/linea-12-del-metro-cierra-12-estaciones-por-seis-meses/',
				},
				{
					titulo		: 'Rodrigo Medina, gobernador de Nuevo León, acusado de irregularidades en proyecto hidráulico Monterrey VI.',
					fecha			: '7 de diciembre de 2014',
					iframe 		: true,
					fuente		: 'http://www.elfinanciero.com.mx/monterrey/vi-un-proyecto-controversial.html',
				},
				{
					titulo		: 'Hijos de Martha Sahagún, exprimera dama, vinculados a contratos de Oceanografía con PEMEX por 5 mil MDP.',
					fecha			: '2 de marzo de 2014',
					iframe 		: true,
					fuente		: 'http://www.jornada.unam.mx/ultimas/2014/03/02/los-hijos-de-marta-sahagun-gestores-de-oceanografia-9006.html',
				},
				{
					titulo		: 'Revelan “Casa Blanca” de 80 MDP, propiedad de la primera dama, construida por Grupo Higa, ganador de la licitación del tren MEX-QRO.',
					fecha			: '9 de noviembre de 2014',
					iframe 		: true,
					fuente		: 'http://aristeguinoticias.com/0911/mexico/la-casa-blanca-de-enrique-pena-nieto/',
				},
				{
					titulo		: 'Oceanografía es inhabilitada por irregularidades con PEMEX y embargada por fraude a Banamex por 400 MDD.',
					fecha			: '12-28 de febrero 2014',
					iframe 		: true,
					fuente		: 'http://www.excelsior.com.mx/nacional/2014/03/01/946200',
				},
				{
					titulo		: 'José Luis Madrigal Figueroa, alcalde de Numarán, MICH, acusado de promover colusión entre funcionarios y crimen organizado.',
					fecha			: '25 de octubre de 2014',
					iframe 		: true,
					fuente		: 'http://www.excelsior.com.mx/nacional/2014/10/25/988741',
				},
				{
					titulo		: 'Investigan cuentas en Texas de Luis Armando Jerezano Treviño, juez mexicano, por tener 1.5 MDD vinculados al crimen organizado.',
					fecha			: '4 de febrero de 2014',
					iframe 		: true,
					fuente		: 'http://archivo.eluniversal.com.mx/nacion-mexico/2014/investiga-la-dea-a-juez-mexicano-984703.html',
				},
				{
					titulo		: 'Multa CNBV con 30 MDP a Banamex por fraude de Oceanografía.',
					fecha			: '15 de octubre de 2014',
					iframe 		: true,
					fuente		: 'http://www.jornada.unam.mx/ultimas/2014/10/15/multan-a-banamex-por-29-9-mdp-por-fallas-que-derivaron-en-fraude-de-oceanografia-3880.html',
				},
				{
					titulo		: 'Ismael Pérez Ordaz, alcalde de Celaya, denuncia que dirigentes panistas condicionan acceso a recursos federales.',
					fecha			: '13 de enero de 2014',
					iframe 		: true,
					fuente		: 'http://www.sdpnoticias.com/nacional/2014/01/13/alcalde-del-pan-revela-moches',
				},
				{
					titulo		: 'Héctor Villarreal, exsecretario de Finanzas de COAH, se declara culpable de lavado de dinero por 10 MDD en EUA.',
					fecha			: '17 de septiembre de 2014',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2014/09/ex-tesorero-de-humberto-moreira-se-declara-en-eu-culpable-de-lavado-de-dinero/',
				},
			],
		},
		{
			anio: '2013',
			eventos : [
				{
					titulo		: 'Tomas Yarrington, exgobernador de Tamaulipas, acusado de permitir paso a cargamentos de droga hacia Texas.',
					fecha			: '3 de diciembre de 2013',
					iframe 		: true,
					fuente		: 'http://expansion.mx/nacional/2013/12/02/eu-busca-a-tomas-yarrington-por-narcotrafico-y-lavado-de-dinero?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+cnnmexico%2Fnacional+(Nacional)',
				},
				{
					titulo		: 'Desabasto de agua en Bacanuchi, SON, causado por presa en el rancho del gobernador Guillermo Padrés.',
					fecha			: '8 de septiembre de 2014',
					iframe 		: true,
					fuente		: 'http://www.excelsior.com.mx/nacional/2014/09/08/980583',
				},
				{
					titulo		: 'Diputados cobran mochesa alcaldes para acceder a recursos federales de obra pública.',
					fecha			: '26 de noviembre de 2013',
					iframe 		: true,
					fuente		: 'http://aristeguinoticias.com/2611/mexico/como-cobran-diputados-afines-a-villareal-moche-a-alcaldes/',
				},
				{
					titulo		: 'Senador Jorge Luis Preciado acusado de ofrecer 500 mil pesos a otro senador a cambio de votar favorablemente iniciativas de EPN.',
					fecha			: '4 de septiembre de 2014',
					iframe 		: true,
					fuente		: 'http://www.excelsior.com.mx/nacional/2014/09/04/979780',
				},
				{
					titulo		: 'Empleados del fideicomiso de becas de la ALDF acusados de falsificar firmas para desviar 8 MDP.',
					fecha			: '27 de octubre de 2013',
					iframe 		: true,
					fuente		: 'https://noticias.terra.com.mx/mexico/df/pgjdf-indaga-fraude-en-programa-de-becas-de-aldf,53913159b2da1410VgnVCM20000099cceb0aRCRD.html',
				},
				{
					titulo		: 'Circula video deLa Tutay Rodrigo Vallejo, hijo del gobernador de Michoacán, discutiendo crisis política del estado.',
					fecha			: '29 de julio de 2014',
					iframe 		: true,
					fuente		: 'http://www.excelsior.com.mx/nacional/2014/07/29/973386',
				},
				{
					titulo		: 'Revelan permisos de construcción apócrifos en áreas fuertemente dañadas por las tormentas “Ingrid” y “Manuel” en Acapulco.',
					fecha			: '25 de octubre de 2013',
					iframe 		: true,
					fuente		: 'http://m.adnpolitico.com/noticias/2013/10/25/las-noticias-de-los-diarios-del-viernes-25-de-octubre',
				},
				{
					titulo		: 'Alcaldes en AGS denuncian que Luis Villarreal, líder del PAN en C. Diputados, exige mochesa cambio de recursos federales.',
					fecha			: '18 de marzo de 2014',
					iframe 		: true,
					fuente		: 'https://noticias.terra.com.mx/mexico/estados/panistas-exhiben-red-de-villarreal-en-aguascalientes,2c279355495d4410VgnVCM5000009ccceb0aRCRD.html',
				},
				{
					titulo		: 'Revelan que FOVISSTE avaló créditos fraudulentos con pérdida para el erario por 1,500 MDP entre 2008-2011.',
					fecha			: '7 de octubre de 2013',
					iframe 		: true,
					fuente		: 'http://archivo.eluniversal.com.mx/nacion-mexico/2013/defraudan-1-500-millones-a-fovissste-956395.html',
				},
				{
					titulo		: 'Jorge Torres, gobernador interino COAH, acusado de desviar 2.8 MDD a cuentas en el extranjero.',
					fecha			: '26 de septiembre de 2013',
					iframe 		: true,
					fuente		: 'http://aristeguinoticias.com/2609/mexico/acusan-en-eu-a-sucesor-de-moreira-por-desvio-de-2-8-mdd/',
				},
				{
					titulo		: 'Revelan red de trata en el AICM manejada por autoridades migratorias y policías federales.',
					fecha			: '23 de septiembre de 2013',
					iframe 		: true,
					fuente		: 'http://archivo.eluniversal.com.mx/ciudad-metropoli/2013/corrupcion-en-el-aicm-facilita-trata-952857.html',
				},
				{
					titulo		: 'Revelan que Fernando Espino Arévalo, asambleísta en DF y líder del sindicato del Metro, tiene a 22 familiares en la nómina.',
					fecha			: '29 de julio de 2013',
					iframe 		: true,
					fuente		: 'http://archivo.eluniversal.com.mx/ciudad-metropoli/2013/lider-del-metro-tiene-en-nomina-a-22-familiares-938922.html',
				},
				{
					titulo		: 'Empresarios denuncian a Gustavo Adolfo Roque, Dir. Jurídico en Tlalpan (DF), por extorsión.',
					fecha			: '25 de julio de 2013',
					iframe 		: true,
					fuente		: 'http://www.razon.com.mx/spip.php?article180326',
				},
				{
					titulo		: 'Revelan que hijo de Luis Armando Reynoso, exgobernador de AGS, depositó 58 MDP a cuentas personales durante gestión de su padre.',
					fecha			: '23 de junio de 2013',
					iframe 		: true,
					fuente		: 'http://aristeguinoticias.com/1406/mexico/caso-reynoso-femat-en-3-anos-le-depositaron-58-mdp-al-hijo-del-gobernador-de-aguascalientes/',
				},
				{
					titulo		: 'César Duarte, gobernadorde Chihuahua, registra marca comercial ante el IMPI con el mismo domicilio fiscal que empresa proveedora de su gobierno.',
					fecha			: '10 de junio de 2013',
					iframe 		: true,
					fuente		: 'http://www.sinembargo.mx/12-11-2015/1548005',
				},
				{
					titulo		: 'Constructores denuncian a Raymundo Collins, titular de INVI-DF, por extorsión y cobros indebidos.',
					fecha			: '5 de junio de 2013',
					iframe 		: true,
					fuente		: 'http://economia.terra.com.mx/finanzas/df-denuncian-constructores-extorsion-por-parte-del-invi,a6786883f3e04410VgnCLD200000bbcceb0aRCRD.html',
				},
				{
					titulo		: 'Verificadores de PROFECO intervienen restaurante Maximo Bistrot a petición de hija del titular, Humberto Benítez Treviño.',
					fecha			: '28 de abril de 2013',
					iframe 		: true,
					fuente		: 'http://aristeguinoticias.com/2804/mexico/lady-profeco-mete-en-problemas-a-su-papa/',
				},
				{
					titulo		: 'Fidel Herrera, exgobernador de Veracruz, acusado de recibir 12 MDD del narcotráfico para su campaña.',
					fecha			: '19 de abril de 2013',
					iframe 		: true,
					fuente		: 'http://www.univision.com/noticias/narcotrafico/narcotraficante-dice-haber-financiado-campana-de-fidel-herrera',
				},
				{
					titulo		: 'Elba Esther Gordillo es detenida por la PGR acusada de malversación de fondos del SNTE.',
					fecha			: '26 de febrero de 2013',
					iframe 		: true,
					fuente		: 'http://expansion.mx/nacional/2013/02/26/la-pgr-detiene-a-elba-esther-gordillo-por-presunto-desvio-de-recursos',
				},
				{
					titulo		: 'Delegado de Coyoacán, Mauricio Toledo, exige 1 MDP para no clausurar una construcción.',
					fecha			: '25 de febrero de 2013',
					iframe 		: true,
					fuente		: 'http://www.animalpolitico.com/2013/02/acusan-de-extorsion-por-1-6-mdp-a-delegado-de-coyoacan/',
				},
				{
					titulo		: 'Carlos Romero Deschamps, líder petrolero, regala Ferrari Enzo de 2 MDD a su hijo.',
					fecha			: '24 de febrero de 2013',
					iframe 		: true,
					fuente		: 'http://www.proceso.com.mx/334462',
				},
				{
					titulo		: 'La TV francesa exhibe lujos y extravagancias de Arturo Montiel mientras fue gobernador del Edomex.',
					fecha			: '21 de febrero de 2013',
					iframe 		: true,
					fuente		: 'http://www.sinembargo.mx/21-02-2013/536218',
				},
				{
					titulo		: 'Allegados a Humberto Moreira, exgobernador COAH, vinculados con fraude fiscal a través de empresas textiles por 1,650 MDP.',
					fecha			: '31 de enero de 2013',
					iframe 		: true,
					fuente		: 'http://aristeguinoticias.com/3101/mexico/investiga-sat-megafraude-en-coahuila',
				},
				{
					titulo		: 'Revelan red de sobornos en PEMEX; SIEMENS habría pagado 29 MDP para obtener contratos.',
					fecha			: '28 de enero de 2013',
					iframe 		: true,
					fuente		: 'http://www.reporteindigo.com/reporte/mexico/destapan-corrupcion-en-pemex',
				},
			],
		},
		{
			anio: '2012',
			eventos : [
				{
					titulo		: 'Revelan que Walmart pagó 24 MDD a funcionarios en México.',
					fecha			: '17 de diciembre de 2012',
					iframe 		: true,
					fuente		: 'http://www.nytimes.com/2012/12/18/business/walmart-bribes-teotihuacan.html?pagewanted=all&_r=0',
				},
				{
					titulo		: 'Revelan que HSBC lavó 880 MDD para el cártel de Sinaloa entre 2006-2010.',
					fecha			: '12 de diciembre de 2012',
					iframe 		: true,
					fuente		: 'http://aristeguinoticias.com/1212/mexico/hsbc-lavo-881-mdd-del-chapo-guzman-y-narcos-colombianos-pagara-multa-de-1900-mdd',
				},
			],
		},
	],
	imagenes: [

		//////////////////////////////////////////// Cielo
		{
			// Datos de las imágenes del fondo
			pos_img		: 'centro',
			start			: '0',
			end			: '500',
			start_size	: '0.6',
			end_size		: '1.1',
			start_opa	: '1',
			end_opa		: '0',
			ruta_imagen	: "assets/imgs/img--cielo__0.jpg",
			z_index 		: "5",
		},
		//////////////////////////////////////////// Piso
		{
			pos_img		: 'abajo',
			start			: '1720',
			end			: '2080',
			end_size		: '0.55',
			ruta_imagen	: "assets/imgs/img__piso-3.jpg",
			z_index 		: "33",
			especiales	: 'horizontal--100'
		},
		{
			pos_img		: 'abajo',
			start			: '1115',
			end			: '2080',
			start_size	: '0.75',
			end_size		: '0.75',
			ruta_imagen	: "assets/imgs/img__piso-21.png",
			z_index 		: "32",
		},
		{
			pos_img		: 'abajo',
			start			: '1115',
			end			: '2080',
			start_size	: '0.75',
			end_size		: '0.75',
			ruta_imagen	: "assets/imgs/img__piso-2.jpg",
			z_index 		: "31",
		},
		{
			pos_img		: 'abajo',
			start			: '0',
			end			: '1115',
			start_size	: '0.5',
			end_size		: '0.6',
			ruta_imagen	: "assets/imgs/img__piso-1.jpg",
			z_index 		: "31",
			especiales	: 'horizontal--100'
		},
		//////////////////////////////////////////// Edificios
		/*
			{
				pos_img		: 'derecha',
				start			: '1650',
				end			: '1900',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-32.png",
				z_index 		: "34",
			},
			{
				pos_img		: 'izquierda',
				start			: '1650',
				end			: '1900',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-32.png",
				z_index 		: "34",
			},
			{
				pos_img		: 'derecha',
				start			: '1580',
				end			: '1745',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-31.png",
				z_index 		: "34",
			},
			{
				pos_img		: 'derecha',
				start			: '1470',
				end			: '1635',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-30.png",
				z_index 		: "34",
			},
			{
				pos_img		: 'izquierda',
				start			: '1470',
				end			: '1635',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-30.png",
				z_index 		: "34",
			},
			{
				pos_img		: 'izquierda',
				start			: '1420',
				end			: '1585',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-29.png",
				z_index 		: "34",
			},
			{
				pos_img		: 'derecha',
				start			: '1340',
				end			: '1505',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-28.png",
				z_index 		: "34",
			},
			
			{
				pos_img		: 'izquierda',
				start			: '1340',
				end			: '1505',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-28.png",
				z_index 		: "34",
			},
			{
				pos_img		: 'derecha',
				start			: '1260',
				end			: '1425',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-27.png",
				z_index 		: "34",
			},
			{
				pos_img		: 'izquierda',
				start			: '1260',
				end			: '1425',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-27.png",
				z_index 		: "34",
			},
			{
				pos_img		: 'derecha',
				start			: '1180',
				end			: '1345',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-26.png",
				z_index 		: "34",
			},
			{
				pos_img		: 'derecha',
				start			: '1140',
				end			: '1305',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-24.png",
				z_index 		: "34",
			},
			{
				pos_img		: 'derecha',
				start			: '1100',
				end			: '1265',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-23.png",
				z_index 		: "34",
			},
			{
				pos_img		: 'izquierda',
				start			: '1100',
				end			: '1265',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-24.png",
				z_index 		: "34",
			},
			{
				pos_img		: 'derecha',
				start			: '855',
				end			: '1020',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__der-21.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'derecha',
				start			: '810',
				end			: '975',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-20.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '810',
				end			: '975',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-20.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '740',
				end			: '905',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-19.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'derecha',
				start			: '715',
				end			: '880',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-18.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '715',
				end			: '880',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-18.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '690',
				end			: '715',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-17.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '665',
				end			: '690',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-16.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '640',
				end			: '805',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-15.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '615',
				end			: '780',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-14.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'derecha',
				start			: '590',
				end			: '755',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-13.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '590',
				end			: '755',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-13.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '535',
				end			: '700',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-12.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '505',
				end			: '670',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-11.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'derecha',
				start			: '475',
				end			: '640',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-10.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '475',
				end			: '640',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-10.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'derecha',
				start			: '445',
				end			: '610',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-09.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '445',
				end			: '610',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-09.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'derecha',
				start			: '415',
				end			: '580',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-08.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '415',
				end			: '580',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-08.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'derecha',
				start			: '365',
				end			: '530',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-07.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '365',
				end			: '530',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-07.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'derecha',
				start			: '335',
				end			: '500',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-06.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'derecha',
				start			: '295',
				end			: '460',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-05.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '295',
				end			: '460',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-05.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'derecha',
				start			: '235',
				end			: '400',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-04.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '235',
				end			: '400',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__izq-04.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'derecha',
				start			: '165',
				end			: '330',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__der-03.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '165',
				end			: '330',
				end_size		: '2',
				ruta_imagen	: "assets/imgs/img--edif__izq-03.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'derecha',
				start			: '15',
				end			: '180',
				start_size	: '0.15',
				end_size		: '2.15',
				ruta_imagen	: "assets/imgs/img--edif__der-02.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '15',
				end			: '180',
				start_size	: '0.15',
				end_size		: '2.15',
				ruta_imagen	: "assets/imgs/img--edif__izq-02.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'derecha',
				start			: '3',
				end			: '155',
				start_size	: '0.6',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__der-01.png",
				z_index 		: "20",
			},
			{
				pos_img		: 'izquierda',
				start			: '3',
				end			: '155',
				start_size	: '0.6',
				end_size		: '2.6',
				ruta_imagen	: "assets/imgs/img--edif__izq-01.png",
				z_index 		: "20",
			},
		*/
		{
			pos_img		: 'centro',
			start			: '1770',
			end			: '2080',
			end_size		: '2.0',
			ruta_imagen	: "assets/imgs/img--edif__centro-32.png",
			z_index 		: "34",
		},
		{
			pos_img		: 'centro',
			start			: '1610',
			end			: '1775',
			end_size		: '2',
			ruta_imagen	: "assets/imgs/img--edif__centro-30.png",
			z_index 		: "34",
		},
		{
			pos_img		: 'izquierda',
			start			: '1540',
			end			: '1705',
			end_size		: '2',
			ruta_imagen	: "assets/imgs/img--edif__centro-29.png",
			z_index 		: "34",
		},
		{
			pos_img		: 'centro',
			start			: '1470',
			end			: '1635',
			end_size		: '2',
			ruta_imagen	: "assets/imgs/img--edif__centro-28.png",
			z_index 		: "34",
		},
		{
			pos_img		: 'centro',
			start			: '1360',
			end			: '1525',
			end_size		: '2',
			ruta_imagen	: "assets/imgs/img--edif__centro-27.png",
			z_index 		: "34",
		},
		{
			pos_img		: 'centro',
			start			: '1270',
			end			: '1435',
			end_size		: '2',
			ruta_imagen	: "assets/imgs/img--edif__centro-26.png",
			z_index 		: "34",
		},
		{
			pos_img		: 'centro',
			start			: '1160',
			end			: '1325',
			end_size		: '2',
			ruta_imagen	: "assets/imgs/img--edif__centro-24.png",
			z_index 		: "34",
		},
		{
			pos_img		: 'centro',
			start			: '1070',
			end			: '1235',
			end_size		: '2',
			ruta_imagen	: "assets/imgs/img--edif__centro-23.png",
			z_index 		: "34",
		},
		{
			pos_img		: 'derecha',
			start			: '855',
			end			: '1020',
			end_size		: '2.6',
			ruta_imagen	: "assets/imgs/img--edif__der-21.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'centro',
			start			: '810',
			end			: '975',
			end_size		: '2.6',
			ruta_imagen	: "assets/imgs/img--edif__centro-20.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'izquierda',
			start			: '740',
			end			: '905',
			end_size		: '2.6',
			ruta_imagen	: "assets/imgs/img--edif__izq-19.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'centro',
			start			: '715',
			end			: '880',
			end_size		: '2.6',
			ruta_imagen	: "assets/imgs/img--edif__centro-18.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'izquierda',
			start			: '690',
			end			: '715',
			end_size		: '2.6',
			ruta_imagen	: "assets/imgs/img--edif__izq-17.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'izquierda',
			start			: '665',
			end			: '690',
			end_size		: '2.6',
			ruta_imagen	: "assets/imgs/img--edif__izq-16.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'izquierda',
			start			: '640',
			end			: '805',
			end_size		: '2.6',
			ruta_imagen	: "assets/imgs/img--edif__izq-15.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'izquierda',
			start			: '615',
			end			: '780',
			end_size		: '2.6',
			ruta_imagen	: "assets/imgs/img--edif__izq-14.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'centro',
			start			: '590',
			end			: '755',
			end_size		: '2.6',
			ruta_imagen	: "assets/imgs/img--edif__centro-13.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'izquierda',
			start			: '535',
			end			: '700',
			end_size		: '2.6',
			ruta_imagen	: "assets/imgs/img--edif__izq-12.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'izquierda',
			start			: '505',
			end			: '670',
			end_size		: '2.6',
			ruta_imagen	: "assets/imgs/img--edif__izq-11.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'centro',
			start			: '475',
			end			: '640',
			end_size		: '2.6',
			ruta_imagen	: "assets/imgs/img--edif__centro-10.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'centro',
			start			: '445',
			end			: '610',
			end_size		: '2.6',
			ruta_imagen	: "assets/imgs/img--edif__centro-09.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'centro',
			start			: '415',
			end			: '580',
			end_size		: '2.6',
			ruta_imagen	: "assets/imgs/img--edif__centro-08.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'centro',
			start			: '365',
			end			: '530',
			end_size		: '2.6',
			ruta_imagen	: "assets/imgs/img--edif__centro-07.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'derecha',
			start			: '335',
			end			: '500',
			end_size		: '2',
			ruta_imagen	: "assets/imgs/img--edif__der-06.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'centro',
			start			: '295',
			end			: '460',
			end_size		: '2.6',
			ruta_imagen	: "assets/imgs/img--edif__centro-05.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'centro',
			start			: '235',
			end			: '400',
			end_size		: '2',
			ruta_imagen	: "assets/imgs/img--edif__centro-04.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'centro',
			start			: '165',
			end			: '330',
			end_size		: '2',
			ruta_imagen	: "assets/imgs/img--edif__centro-03.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'centro',
			start			: '15',
			end			: '180',
			start_size	: '0.15',
			end_size		: '2.15',
			ruta_imagen	: "assets/imgs/img--edif__centro-02.png",
			z_index 		: "20",
		},
		{
			pos_img		: 'centro',
			start			: '3',
			end			: '155',
			start_size	: '0.6',
			end_size		: '2.6',
			ruta_imagen	: "assets/imgs/img--edif__centro-01.png",
			z_index 		: "20",
		},
		//////////////////////////////////////////// Árboles
		/// Aquí más árboles
		/*
		{
			pos_img		: 'centro',
			start			: '1130',
			end			: '1230',
			start_size	: '0.04',
			end_size		: '0.04',
			ruta_imagen	: "assets/imgs/img__arbol-41.png",
			z_index 		: "49",
		},
		{
			pos_img		: 'centro',
			start			: '1230',
			end			: '1795',
			start_size	: '0.04',
			end_size		: '1.74',
			ruta_imagen	: "assets/imgs/img__arbol-41.png",
			z_index 		: "49",
		},
		///
		{
			pos_img		: 'centro',
			start			: '1125',
			end			: '1155',
			start_size	: '0.1',
			end_size		: '0.1',
			ruta_imagen	: "assets/imgs/img__arbol-41.png",
			z_index 		: "49",
		},
		///
		{
			pos_img		: 'centro',
			start			: '1155',
			end			: '1650',
			start_size	: '0.1',
			end_size		: '1.8',
			ruta_imagen	: "assets/imgs/img__arbol-41.png",
			z_index 		: "49",
		},
		///
		{
			pos_img		: 'centro',
			start			: '1130',
			end			: '1555',
			start_size	: '0.25',
			end_size		: '1.95',
			ruta_imagen	: "assets/imgs/img__arbol-41.png",
			z_index 		: "49",
		},
		///
		{
			pos_img		: 'centro',
			start			: '1120',
			end			: '1475',
			start_size	: '0.46',
			end_size		: '2.16',
			ruta_imagen	: "assets/imgs/img__arbol-41.png",
			z_index 		: "49",
		},
		///
		{
			pos_img		: 'centro',
			start			: '1115',
			end			: '1400',
			start_size	: '1',
			end_size		: '2.7',
			ruta_imagen	: "assets/imgs/img__arbol-41.png",
			z_index 		: "49",
		},
		*/
		{
			pos_img		: 'centro',
			start			: '0',
			end			: '1115',
			start_size	: '0.04',
			end_size		: '0.04',
			ruta_imagen	: "assets/imgs/img__arbol-11.png",
			z_index 		: "49",
		},
		///
		{
			pos_img		: 'centro',
			start			: '0',
			end			: '1115',
			start_size	: '0.1',
			end_size		: '0.1',
			ruta_imagen	: "assets/imgs/img__arbol-11.png",
			z_index 		: "49",
		},
		///
		{
			pos_img		: 'centro',
			start			: '0',
			end			: '1115',
			start_size	: '0.25',
			end_size		: '0.25',
			ruta_imagen	: "assets/imgs/img__arbol-11.png",
			z_index 		: "49",
		},
		{
			pos_img		: 'centro',
			start			: '950',
			end			: '1115',
			start_size	: '0.7',
			end_size		: '0.7',
			ruta_imagen	: "assets/imgs/img__arbol-11.png",
			z_index 		: "49",
		},
		///
		/*
		{
			pos_img		: 'centro',
			start			: '800',
			end			: '1915',
			start_size	: '0.1',
			end_size		: '1.8',
			ruta_imagen	: "assets/imgs/img__arbol-11.png",
			z_index 		: "49",
		},
		*/
		///
		{
			pos_img		: 'centro',
			start			: '700',
			end			: '1455',
			start_size	: '0.1',
			end_size		: '2',
			ruta_imagen	: "assets/imgs/img__arbol-11.png",
			z_index 		: "49",
		},
		///
		{
			pos_img		: 'centro',
			start			: '600',
			end			: '1455',
			start_size	: '0.1',
			end_size		: '1.8',
			ruta_imagen	: "assets/imgs/img__arbol-11.png",
			z_index 		: "49",
		},
		///
		{
			pos_img		: 'centro',
			start			: '500',
			end			: '1405',
			start_size	: '0.1',
			end_size		: '1.8',
			ruta_imagen	: "assets/imgs/img__arbol-11.png",
			z_index 		: "49",
		},
		///
		{
			pos_img		: 'centro',
			start			: '400',
			end			: '1335',
			start_size	: '0.1',
			end_size		: '1.8',
			ruta_imagen	: "assets/imgs/img__arbol-11.png",
			z_index 		: "49",
		},
		///
		{
			pos_img		: 'centro',
			start			: '300',
			end			: '1255',
			start_size	: '0.1',
			end_size		: '1.8',
			ruta_imagen	: "assets/imgs/img__arbol-11.png",
			z_index 		: "49",
		},
		///
		{
			pos_img		: 'centro',
			start			: '200',
			end			: '1155',
			start_size	: '0.1',
			end_size		: '1.8',
			ruta_imagen	: "assets/imgs/img__arbol-11.png",
			z_index 		: "49",
		},
		///
		{
			pos_img		: 'centro',
			start			: '100',
			end			: '1055',
			start_size	: '0.1',
			end_size		: '1.8',
			ruta_imagen	: "assets/imgs/img__arbol-11.png",
			z_index 		: "49",
		},
		///
		{
			pos_img		: 'centro',
			start			: '0',
			end			: '955',
			start_size	: '0.1',
			end_size		: '1.8',
			ruta_imagen	: "assets/imgs/img__arbol-11.png",
			z_index 		: "49",
		},
		///
		{
			pos_img		: 'centro',
			start			: '0',
			end			: '955',
			start_size	: '0.18',
			end_size		: '1.88',
			ruta_imagen	: "assets/imgs/img__arbol-11.png",
			z_index 		: "49",
		},
		///
		{
			pos_img		: 'centro',
			start			: '0',
			end			: '955',
			start_size	: '0.46',
			end_size		: '2.16',
			ruta_imagen	: "assets/imgs/img__arbol-11.png",
			z_index 		: "49",
		},
		///
		{
			pos_img		: 'centro',
			start			: '0',
			end			: '955',
			start_size	: '1',
			end_size		: '2.7',
			ruta_imagen	: "assets/imgs/img__arbol-11.png",
			z_index 		: "49",
		},
		
		//////////////////////////////////////////// Calle
		/// Glorieta Zocalo
		{
			pos_img		: 'centro',
			start			: '1770',
			end			: '2080',
			end_size		: '0.7',
			ruta_imagen	: "assets/imgs/img--glorieta-09.png",
			z_index 		: "33",
		},
		/// Glorieta bandera
		{
			pos_img		: 'centro',
			start			: '1770',
			end			: '2040',
			end_size		: '1.2',
			ruta_imagen	: "assets/imgs/img--glorieta-08.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '921',
			end			: '1101',
			end_size		: '1.2',
			ruta_imagen	: "assets/imgs/img--camellon-03.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '921',
			end			: '1101',
			start_size	: '0.41',
			end_size		: '1.61',
			ruta_imagen	: "assets/imgs/img--camellon-03.png",
			z_index 		: "51",
		},
		/// Glorieta +43
		{
			pos_img		: 'centro',
			start			: '950',
			end			: '1130',
			end_size		: '1.2',
			ruta_imagen	: "assets/imgs/img--glorieta-07.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '921',
			end			: '1101',
			end_size		: '1.2',
			ruta_imagen	: "assets/imgs/img--camellon-03.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '921',
			end			: '1101',
			start_size	: '0.41',
			end_size		: '1.61',
			ruta_imagen	: "assets/imgs/img--camellon-03.png",
			z_index 		: "51",
		},
		/// Glorieta circular
		{
			pos_img		: 'centro',
			start			: '781',
			end			: '961',
			end_size		: '1.2',
			ruta_imagen	: "assets/imgs/img--glorieta-06.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '765',
			end			: '945',
			end_size		: '1.2',
			ruta_imagen	: "assets/imgs/img--camellon-03.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '720',
			end			: '900',
			start_size	: '0.41',
			end_size		: '1.61',
			ruta_imagen	: "assets/imgs/img--camellon-03.png",
			z_index 		: "51",
		},
		/// Glorieta Cristobal
		{
			pos_img		: 'centro',
			start			: '580',
			end			: '780',
			end_size		: '1.2',
			ruta_imagen	: "assets/imgs/img--glorieta-05.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '570',
			end			: '750',
			start_size	: '0.08',
			end_size		: '1.28',
			ruta_imagen	: "assets/imgs/img--camellon-02.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '570',
			end			: '750',
			start_size	: '0.42',
			end_size		: '1.61',
			ruta_imagen	: "assets/imgs/img--camellon-02.png",
			z_index 		: "51",
		},
		///
		///
		{
			pos_img		: 'abajo',
			start			: '0',
			end			: '390',
			start_size	: '0.04',
			end_size		: '0.04',
			ruta_imagen	: "assets/imgs/img--camellon-01.png",
			z_index 		: "50",
		},
		{
			pos_img		: 'abajo',
			start			: '0',
			end			: '395',
			start_size	: '0.1',
			end_size		: '0.1',
			ruta_imagen	: "assets/imgs/img--camellon-01.png",
			z_index 		: "50",
		},
		/// Glorieta Cuitlahuac
		{
			pos_img		: 'centro',
			start			: '400',
			end			: '580',
			start_size	: '0.04',
			end_size		: '1.24',
			ruta_imagen	: "assets/imgs/img--glorieta-04.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '395',
			end			: '550',
			start_size	: '0.1',
			end_size		: '1.04',
			ruta_imagen	: "assets/imgs/img--camellon-01.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '360',
			end			: '540',
			start_size	: '0.1',
			end_size		: '1.3',
			ruta_imagen	: "assets/imgs/img--camellon-01.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '340',
			end			: '520',
			start_size	: '0.1',
			end_size		: '1.3',
			ruta_imagen	: "assets/imgs/img--camellon-01.png",
			z_index 		: "51",
		},
		/// Glorieta Palma
		{
			pos_img		: 'centro',
			start			: '280',
			end			: '460',
			start_size	: '0.1',
			end_size		: '1.3',
			ruta_imagen	: "assets/imgs/img--glorieta-03.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '280',
			end			: '460',
			start_size	: '0.14',
			end_size		: '1.34',
			ruta_imagen	: "assets/imgs/img--camellon-01.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '280',
			end			: '460',
			start_size	: '0.41',
			end_size		: '1.61',
			ruta_imagen	: "assets/imgs/img--camellon-01.png",
			z_index 		: "51",
		},
		/// Glorieta Ángel
		{
			pos_img		: 'centro',
			start			: '140',
			end			: '320',
			start_size	: '0.1',
			end_size		: '1.3',
			ruta_imagen	: "assets/imgs/img--glorieta-02.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '140',
			end			: '320',
			start_size	: '0.14',
			end_size		: '1.34',
			ruta_imagen	: "assets/imgs/img--camellon-01.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '140',
			end			: '320',
			start_size	: '0.41',
			end_size		: '1.61',
			ruta_imagen	: "assets/imgs/img--camellon-01.png",
			z_index 		: "51",
		},
		/// Glorieta Diana
		{
			pos_img		: 'centro',
			start			: '0',
			end			: '180',
			start_size	: '0.1',
			end_size		: '1.3',
			ruta_imagen	: "assets/imgs/img--glorieta-01.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '0',
			end			: '180',
			start_size	: '0.14',
			end_size		: '1.34',
			ruta_imagen	: "assets/imgs/img--camellon-01.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '0',
			end			: '180',
			start_size	: '0.41',
			end_size		: '1.61',
			ruta_imagen	: "assets/imgs/img--camellon-01.png",
			z_index 		: "51",
		},
		{
			pos_img		: 'abajo',
			start			: '0',
			end			: '180',
			start_size	: '1',
			end_size		: '2.2',
			ruta_imagen	: "assets/imgs/img--camellon-01.png",
			z_index 		: "51",
		},
		//////////////////////////////////////////// Entrada
		{
			// Datos de las imágenes del fondo
			pos_img		: 'centro', // Alineación de la imagen en la capa -> arriba, abajo, izquierda, derecha, centro
			start			: '0',
			end			: '10',
			start_size	: '0.8',
			end_size		: '2.5',
			ruta_imagen	: "assets/imgs/img--entrada.png",
			z_index 		: "60",
		},
	],
};

Handlebars.registerHelper('el_index', function(indx) {
	if ( indx != 0 ) {
	  return '_oculto';
	}
});